window.lang = {
    'brandtitle': 'Cloud Service',
    'loginpagetitle': 'Cloud Service login',
    'newbrandtitle': 'OPPO Cloud',
    'username': 'Account',
    'password': 'Passcode',
    'loginBtn': 'Login',
    'resetpassword': 'Forgot Passcode',
    'register': 'Create an Account',
    'bottomText': 'Copyright © {nowyear} OPPO. All rights reserved.',
    'overtime': 'For security, you need to log in again if no operation is performed in 15 minutes.',
    'loginBtnIng': 'Logging in...',
    'systembusy': 'System is busy. Please retry later',
    'phonelogin': 'Please enter your phone number',
    'maillogin': 'Please enter your email address',
    'passwordlogin': 'Please enter your passcode',
    'userphonelogin': 'Log in with your phone number',
    'useremaillogin': 'Log in with your email box',
    'searchcycode': 'Search a country/region',
    'selectcycode': 'Select a country code',
    'login_msg_nophone': 'Please enter your phone number',
    'login_msg_noemmail': 'Please enter your email address',
    'login_msg_nocycode': 'Please select a country code',
    'login_msg_nopwd': 'Please enter your password',
    'backtoold': 'Back to the old version',
    'bbs': 'Forum feedback',
    'logoutBtn': 'Log out',
    'cloudService': 'Cloud Service',
    'gonewversion': 'Go to the new version',
    'phototitle': 'Photos',
    'videotitle': 'Videos',
    'photorecycle': 'Recycle Bin',
    'photoselect': 'Select',
    'photocancel': 'Cancel',
    'photoselectall': 'Select all loaded photos',
    'downphoto': 'Download original photo',
    'downvideo': 'Download video',
    'nophoto': 'No photo',
    'novideo': 'No video',
    'photorecycletitle': 'Photos and videos show how many days are left before they are recycled',
    'photorecovery': 'Recover',
    'photodeleteall': 'Delete all',
    'photoselectnum': '{size} photos selected',
    'videoselectnum': '{size} videos selected',
    'recycleselectnum': '{size} items selected',
    'deleteselectnum': 'Are you sure you want to delete the selected {size} items permanently?',
    'deletealltitle': 'The deleted items cannot be recovered.',
    'deletevideotitle': 'Are you sure you want to delete the selected {size} videos?',
    'deletevideodesc': 'Selected videos will be removed from the cloud and all phones that have cloud services turned on.',
    'deletephototitle': 'Are you sure you want to delete the selected {size} photos?',
    'deletephotodesc': 'Selected photos will be removed from the cloud and all phones that have cloud services turned on.',
    'note': 'Note',
    'top': 'Top',
    'formatYear': '{year} year',
    'formatDate': '{year} year {month} month {day} day',
    'recBin': 'Recycle bin',
    'addNote': 'Add a new note',
    'save': 'Save',
    'delete': 'Delete',
    'noteListEmpty': 'Empty note list',
    'queryEmpty': 'Empty query result',
    'noteInfoEmpty': 'Click the list on the left to view note details',
    'cleanBin': 'Empty the recycle bin',
    'recoverText': 'Recover',
    'realDelete': 'Delete permanently',
    'cancel': 'Cancel',
    'selNote': '{size} notes selected',
    'edited': 'Edited',
    'saving': 'Saving',
    'saved': 'Saved',
    'cNoteTitle': 'Are you sure you want to empty the recycle bin?',
    'cNoteInfo': 'Files deleted from the recycle bin cannot be recovered.',
    'clean': 'Empty',
    'rNoteTitle': 'Recover the selected {size} notes?',
    'rNoteInfo': 'Also recover these notes on my phone.',
    'rDelNoteTitle': 'Are you sure you want to delete the selected {size} notes permanently?',
    'rDelInfo': 'Permanently deleted notes cannot be recovered.',
    'dNoteTitle': 'Are you sure you want to delete the selected {size} notes?',
    'dNoteInfo': 'Also delete these notes from my phone.',
    'noteAllRecover': 'Recover all notes?',
    'conHolder': 'Search contacts',
    'allCon': 'All contacts',
    'totalCon': '{num} contacts',
    'noGroup': 'Ungrouped',
    'findCon': 'Restore contacts',
    'conInfoEmpty': 'Click the list on the left to view details of contacts',
    'conListEmpty': 'Empty contact list',
    'exportCon': 'Export contacts',
    'selCon': '{size} contacts selected',
    'contact': 'Contacts',
    'searchResult': '{size} contacts found',
    'rConTitle': 'Restore the selected {size} contacts?',
    'rConInfo': 'Also restore these contacts on my phone.',
    'rDelConTitle': 'Permanently delete the selected {size} contacts?',
    'dConTitle': 'Delete the selected {size} contacts?',
    'dConInfo': 'Also delete these contacts from my phone.',
    'fConInfoEmpty': 'Click the list on the left to view details of the restored contacts',
    'findConListEmpty': 'No contacts can be restored',
    'export': 'Export',
    'findConTitle': 'If restored to the state at {time}, the contacts information will change as follows.',
    'findContNum': 'contacts',
    'findAddCon': 'New contacts',
    'findUpCon': 'Modified contacts',
    'findDelCon': 'Deleted contacts',
    'restoring': 'Restoring...',
    'conRestoreFailed': 'Failed restoration of contacts.',
    'retry': 'Retry',
    'remarks': 'Remarks',
    'conRecAllTitle': 'Restore all contacts?',
    'timelineTitle': 'Restore contacts to the state at {time}?',
    'timelineMes': 'Contacts restored to the state at {time}.',
    'smsHolder': 'Search SMS',
    'sms': 'SMS',
    'message': 'Message',
    'notice': 'Notice',
    'smsListEmpty': 'Empty SMS list',
    'noticeListEmpty': 'Empty notice list',
    'smsInfoEmpty': 'Click the list of sessions for details',
    'nowDevice': 'Current device',
    'selSms': '{size} sessions selected',
    'rSmsTitle': 'Recover the selected {size} SMS?',
    'rSmsInfo': 'Also recover these SMS on my phone.',
    'rASmsTitle': 'Recover the selected {size} sessions?',
    'rASmsInfo': 'Also recover these sessions on my phone.',
    'rdASmsTitle': 'Are you sure you want to delete the selected {size} sessions permanently?',
    'rdSmsTitle': 'Permanently delete the selected {size} SMS?',
    'dASmsTitle': 'Delete the selected {size} sessions?',
    'dASmsInfo': 'Also delete these sessions from my phone',
    'dSmsTitle': 'Delete the selected {size} SMS?',
    'dSmsInfo': 'Also delete these SMS from my phone.',
    'allRecovery': 'Recover all',
    'smsRecAllTitle': 'Recover all sessions?',
    'smsTime': '{year} year {month} month {day} day hh:mm',
    'menuphoto': 'Photos',
    'menunote': 'Notes',
    'menusms': 'SMS',
    'menucontact': 'Contacts',
    'menufindphone': 'Find My Phone',
    'menuolddata': 'History Data',
    'menuindex': 'Home',
    'photodelete': 'Delete Photos',
    'loading': 'Loading...',
    'photoleftday': '{day} days left',
    'dialogcancel': 'Cancel',
    'dialogright': 'Confirm',
    'dialogmessage': 'OK',
    'photorecoverytitle': 'Recover the selected {size} items?',
    'photorecoverydesc': 'Also recover these items on my phone.',
    'photodeletetext': 'Delete',
    'phototoday': 'Today',
    'photoyear': '{year} year',
    'backNew': 'Back',
    'totalsms': '{size} SMS',
    'totalphoto': '{size} photos',
    'totalvideo': '{size} videos',
    'totalRec': '{size} items',
    'upbrowsertitle': 'Please upgrade your browser',
    'upbrowserdesc': 'You are using an outdated browser. To continue using Cloud Service,please upgrade your browser. You can do this by:',
    'photorecoverall': 'Recover all photos?',
    'findConInfo': 'Quickly restore Contacts to a previous state',
    'eConTitle': 'Export Contacts in the vCard format to enable its easy import into other devices.',
    'oldaudio': 'Audio',
    'oldtext': 'Text',
    'oldother': 'Other',
    'oldfilename': 'File name',
    'oldfilesize': 'File size',
    'olddownload': 'Download',
    'oldnofile': 'No files',
    'oldnoaudio': 'No audios',
    'oldnotext': 'No files',
    'olddeltetitle': 'Are you sure you want to delete the selected {size} files?',
    'olddelaudiotitle': 'Are you sure you want to delete the selected {size} audios?',
    'olddeltexttitle': 'Are you sure you want to delete the selected {size} files?',
    'oldselfile': '{size} files selected',
    'oldqueryfailed': 'Failed query of history data. Tap to query again',
    'oldfailedtext': 'To ensure that your data is intact, your migrated data needs to be verified again. You can come back to download your personal data after 24:00, Mar.13, 2018. Thanks for your understanding and support.',
    'oldnodata': 'No history data available for download under your account.',
    'smsmodeldesc': 'Switch here to view information of different phones in Cloud Service backup',
    'totalnotes': '{size} notes',
    'headerusedspace': 'Used {size}',
    'headertotalspace': 'Total space {size}',
    'searchsmsresult': 'Found {size} SMS',
    'photobigsize': 'Large',
    'photosmallsize': 'Small',
    'photoheadpos': 'Rapid positioning',
    'photorecycletext': 'The photos and videos in the Recycle Bin will show the remaining time that will be retained, and will be completely deleted when the remaining time is 0 days.',
    'photonorecycle': 'No photos and videos',
    'phototimelinecount': '{count} photos',
    'videotimelinecount': '{count} videos',
    'photodeleteing': 'Deleting...',
    'photodowning': 'Downloading...',
    'photofullscreen': 'Full Screen',
    'photoquitfullscreen': 'Exit Full Screen',
    'knowbrandcloud': 'Learn about Cloud Service Services',
    'useraccounttext': 'Account (mobile number / email address)',
    'createbrandaccount': 'Create an Account',
    'logintitle': 'Mobile phone backup is safe and worry-free, cloud data is always managed',
    'logininputcode': 'Please enter code',
    'logininputusername': 'Please enter Account',
    'condelinfo': 'Selected contacts will be removed from the cloud and all phones that have cloud services enabled.',
    'notdelinfo': 'The selected notes will be removed from the cloud and all phones that have cloud services enabled.',
    'nousername': 'Username not filled in',
    'cloudstoragetext': 'Cloud Storage',
    'introducesectitle': 'New to Cloud Service?',
    'introducesectext': 'Data protection everywhere, easy data transfer',
    'introducesecinfo': 'Cloud Service can securely store your photos, videos, contacts, notes, and other important data. If your phone data is lost or you need a new phone, you can quickly restore your phone data from Cloud Service. Cloud Service offers 5GB free cloud storage and easy options of upgrading to larger cloud storage plans to every user.',
    'introducesectitle1': 'Data security and privacy protection',
    'introducesectext1': 'Multiple security protection mechanisms, strict data encryption',
    'introducesecinfo1': 'Cloud Service takes nothing more seriously than user data security and privacy protection. With the industry-leading cloud storage technologies and disaster recovery strategies, Cloud Service places user data inside multiple protection mechanisms. The strictest encryption algorithms in the industry ensure every piece of user data is encrypted before it is stored and transmitted. No one other than you has access to your data.',
    'introducesectitle2': 'Cloud Sync of Photos',
    'introducesectext2': 'Securely store every treasured moment, easily recall every memory',
    'introducesecinfo2': 'When enabled, Cloud Sync of Photos automatically backs up your photos and videos to Cloud Service as they are. These back-ups can be updated simultaneously across a number of your phones. You can navigate your photos and videos stored in all your phones, be they taken today or stored for years. ',
    'introducesectitle3': 'Optimize phone storage',
    'introducesectext3': 'Optimize phone storage by storing original photos on Cloud Service',
    'introducesecinfo3': 'When you turn on the "Optimize Storage" switch, original photos are stored on Cloud Service, smaller sized versions of these photos are stored on your phone. This frees up more storage on your phone. You can download original photos from Cloud Service to your phone anytime.',
    'introducesectitle4': 'Cloud Back-up of Phone',
    'introducesectext4': 'Automatic periodical backup, quick restoration from Cloud Service',
    'introducesecinfo4': 'Enable Cloud Back-up of Phone to periodically back up your phone\'s SMS, call history, system settings, list of apps, and homescreen layout to Cloud Service, so you can have a peace of mind. With just one tap, you can restore any Cloud Service back-up data to a new phone, it\'s easy and worry-free.',
    'introducesectitle5': 'Cloud Service Storage',
    'introducesectext5': '5GB free storage, multiple upgrade options',
    'introducesecinfo5': 'When you enable Cloud Service, you immediately have 5GB free cloud storage, where you can store your photos, videos, and other data. You can also choose the upgrade plan that best suits your need from a variety of Cloud Service\'s cloud storage upgrade plans to store more data. When you upgrade to a plan of larger storage, you can share this plan with your family members.',
    'introducesectext6': 'Easy management of your cloud data anytime, anywhere',
    'introducesecinfo6': 'You can sign in to Cloud Service\'s official website cloud.oppo.com to review and manage your cloud data from your phone or PC.',
    'introducesectitle7': 'Enable Cloud Service',
    'introducesectext7': '3 easy steps is all you need to activate Cloud Service',
    'introducesecinfo7': 'Just tap "Settings" on the homescreen, then tap "Cloud Service" in the list of setting options, and turn on the switch. You can then enjoy the security and convenience Cloud Service brings to you.',
    'notecollect': 'Collection',
    'smsnodevice': 'No devices',
    'albumstitle': 'Albums',
    'classifyalbum': 'My Albums',
    'smartalbum': 'Smart Albums',
    'showmoretext': 'View All',
    'closemoretext': 'Hide',
    'albumholder': 'People, Location, Object',
    'searchtext': 'Search',
    'photodetail': 'Details',
    'closetext': 'Close',
    'photolabel': 'Name:',
    'photosize': 'Size:',
    'photowidth': 'Dimensions:',
    'photodatetime': 'Time:',
    'photoalbum': 'Album:',
    'photowhtext': '{size} pixels',
    'photosearchresult': 'Search Results',
    'photonoalbum': 'No albums.',
    'deleteitemstitle': 'Delete the selected {size} items?',
    'deleteitemsdesc': 'These items will be deleted from the cloud and your phones that have the cloud service enabled.',
    'albumnopersontitle': 'No people identified.',
    'albumnopersoninfo': 'The People album is automatically generated by identifying people in your photos.',
    'photodownloadtitle': 'Information',
    'photodownloadinfo': 'The download may fail because the size of photos and videos you selected ({totalsize}) exceeds {basesize}. You are advised to download them in batches.',
    'photodownload': 'Continue',
    'photosmart2': 'People',
    'photosmart3': 'Location',
    'photosmart4': 'Object',
    'photoresultinfo': 'Photos Containing {key}',
    'photouploadtext': 'Upload',
    'uploading': 'Uploading',
    'uploadcompleted': 'Uploaded',
    'waitupload': 'Pending',
    'uploadfail': 'Upload failed',
    'spacefulled': 'No space available.',
    'uploadfailcount': ', {count} items fail to be uploaded.',
    'uploadtoalbum': 'Upload to Album',
    'daysremaining': 'Countdown (days): {count}',
    'uploadnoticetext': 'Are you sure you want to stop the upload?',
    'stopupload': 'Stop',
    'photonotice': 'Only JPG, JPEG, and PNG formats are supported.',
    'toastcontent': 'Online video playing is not supported currently,you can download the video and play it locally.',
    'noterecnotice': 'The notes in the Recycle Bin will show the remaining time that will be retained, and will be completely deleted when the remaining time is 0 days.',
    'smsrecnotice': 'The sms in the Recycle Bin will show the remaining time that will be retained, and will be completely deleted when the remaining time is 0 days.',
    'contactsrecnotice': 'The contacts in the Recycle Bin will show the remaining time that will be retained, and will be completely deleted when the remaining time is 0 days.',
    'verifycodeTitle': 'Cloud Service Security Verification',
    'verifycodeDesc': 'To better protect your privacy, we need to verify your identity.',
    'verifycodePhone': 'Verification code sent to<span class="phone">“{phone}”</span>.',
    'verifycodeEmail': 'Verification code sent to <span class="phone">“{email}”</span>.',
    'verifycode': 'Verify',
    'getverifycode': 'Send Again',
    'verifycodeerr': 'Incorrect verification code.',
    'inputverifycode': 'Enter code',
    'getverifycodefirst': 'Obtain a verification code.',
    'verifying': 'Verifying...',
    'cookietip': 'This website uses cookies to store information in your computer. Cookies facilitate the normal running of the website and help improve user experience. By accessing this website, you agree to the use of cookies.',
    'colsecookietip': 'Agree and Close',
    'iosdownloadtip': 'Downloading video files using this browser is not supported by the device. You are advised to visit cloud.oppo.com on a web browser for video download.',
    'knewtext': 'OK',
    'imgdownloadtip': 'Press and hold the photo to save it.',
    'iosvcardtip': 'Exporting contacts using this browser is not supported by the device. You are advised to visit cloud.oppo.com on a web browser for contacts export.',
    'audiotext': 'Recordings',
    'noaudio': 'No Recordings',
    'audiorecycletext': 'Recordings are kept in the recycle bin for 30 days before they are permanently deleted.',
    'standard': 'Standard',
    'conference': 'Conference',
    'interview': 'Interview',
    'call': 'Call',
    'menuclouddrive': 'Cloud Drive',
    'driveallfiles': 'All Files',
    'drivefilename': 'File Name',
    'drivefilesize': 'Size',
    'driveupdatetime': 'Edited On',
    'drivereminds': 'Days Before Deletion',
    'drivenodata': 'No files.',
    'drivedownload': 'Download',
    'drivedeletetitle': 'Delete Selected Files?',
    'drivedeleteinfo': 'Files in Recycle Bin will be deleted after 30 days. ',
    'driverealdeletetitle': 'Permanently Delete Selected Files?',
    'driverealdeleteinfo': 'Permanently deleted files can\'t be recovered.',
    'driveselectall': 'Select all loaded items',
    'photobeautify': 'Cloud Photo Enhancer',
    'allphoto': 'All',
    'beautifydesc': 'Select a photo you want to edit',
    'nomarlstyle': 'Original',
    'savetoasttest': 'Photo saved to the Camera album',
    'reselecttext': 'Select Again',
    'styletip': 'Choose a style',
    'nowexperience': 'Get Started',
    'photonoticetext': 'Format not supported',
    'notetodo': 'Reminders',
    'notetoday': 'Today',
    'notetomorrow': 'Tomorrow',
    'notefuture': 'Upcoming',
    'notecompleted': 'Done',
    'notemarkcompleted': 'Mark as Done',
    'notecancelmark': 'Unmark',
    'menubrowser': 'Browser',
    'bookmark': 'Bookmarks',
    'news': 'News',
    'bookmarktitle': 'Site',
    'collecttime': 'Time Added',
    'newstitle': 'Headline',
    'recycletitle': 'Name',
    'deletenote': 'Delete',
    'nobookmark': 'No Bookmarks',
    'nonews': 'No News Items',
    'norecyledata': 'Recycle Bin Is Empty',
    'deletebookmarkone': 'Delete the selected bookmark?',
    'deletebookmarkother': 'Delete the selected {size} bookmarks?',
    'deletenewsone': 'Delete the selected item?',
    'deletenewsother': 'Delete the selected {size} items?',
    'bookmarkinfo': 'These bookmarks will be deleted from the cloud and any of your devices that have the cloud service enabled.',
    'newsinfo': 'These items will be deleted from the cloud and any of your devices that have the cloud service enabled.',
    'recyleinfo': 'These items will be deleted and cannot be recovered.',
    'recovertitleone': 'Recover the selected item?',
    'recovertitleother': 'Recover the selected {size} items?',
    'recoverinfo': 'Items will also be recovered on your devices.',
    'audiodownloadinfo': 'You have selected too many audio files at once. To increase the success rate of your downloads, these files will be downloaded as multiple compressed files.',
    'photodownloadcontent': 'You have selected too many photos or videos at once. To increase the success rate of your downloads, these files will be downloaded as multiple compressed files.',
    'selectall': 'Select all',
    'photodownloadtips': 'Downloading... Try again later.',
    'notEnoughSpace': 'Insufficient cloud storage',
    'clearallsmsinfo': 'Clear',
    'delbackupinfo': 'Delete all SMS messages from this backup?',
    'menusafe': 'Private Safe',
    'safepsdtitle': 'Security password for HeyTap Cloud',
    'safepsderrone': 'Incorrect password. 1 attempt left.',
    'safepsderrother': 'Incorrect password. {Size} attempts left.',
    'safeclockone': 'Too many failed attempts. Try again in 1 hour.',
    'safeclockother': 'Too many failed attempts. Try again in {size} hours.',
    'nosafephoto': 'No photos',
    'nosafeaudio': 'No audio files',
    'nosafedoc': 'No documents',
    'nosafeothers': 'No files',
    'safedelphototitleone': 'Delete the 1 selected photo?',
    'safedelphototitleother': 'Delete the {size} selected photos?',
    'safedelphotoconone': 'The selected photo will be permanently deleted from \"Private Safe\".',
    'safedelphotoconother': 'The selected photos will be permanently deleted from \"Private Safe\".',
    'safedelphotocountone': '1 photos deleted',
    'safedelphotocountother': '{size} photos deleted',
    'safedelaudiotitleone': 'Delete the 1 selected audio file?',
    'safedelaudiotitleother': 'Delete the {size} selected audio files?',
    'safedelaudioconone': 'The selected audio file will be permanently deleted from \"Private Safe\".',
    'safedelaudioconother': 'The selected audio files will be permanently deleted from \"Private Safe\".',
    'safedelaudiocountone': '1 audio file deleted',
    'safedelaudiocountother': '{size} audio files deleted',
    'safedeldoctitleone': 'Delete the 1 selected document?',
    'safedeldoctitleother': 'Delete the {size} selected documents?',
    'safedeldocconone': 'The selected document will be permanently deleted from \"Private Safe\".',
    'safedeldocconother': 'The selected documents will be permanently deleted from \"Private Safe\".',
    'safedeldoccountone': '1 document deleted',
    'safedeldoccountother': '{size} documents deleted',
    'safedelotherstitleone': 'Delete the 1 selected file?',
    'safedelotherstitleother': 'Delete the {size} selected files?',
    'safedelothersconone': 'The selected file will be permanently deleted from \"Private Safe\".',
    'safedelothersconother': 'The selected files will be permanently deleted from \"Private Safe\".',
    'safedelotherscountone': '1 file deleted',
    'safedelotherscountother': '{size} files deleted',
    'safeName': 'Name',
    'safeSize': 'Size',
    'safeTime': 'Date Uploaded',
    'downloadmodedialogtitle': 'Too many items selected',
    'downloadmodeinfo': 'To ensure that your download will be successful, no more than {size} items can be downloaded at the same time. Deselect some items and try again.',
    'downloadmodetips': 'Each page shows {size} items that can be bulk downloaded. Please download items from only one page at a time to ensure that your download will be successful.',
    'downloadmodetitle': 'Bulk download',
    'downloadpageonekey': 'Download all from this page',
    'downloadmodeselectnumone': '1 selected',
    'downloadmodeselectnum': '{size} selected',
    'selectdownloadname': 'Cloud_album_{size}_items',
    'photopagedownloadname': 'Cloud_album_page_{size}',
    'albumpagedownloadname': 'Cloud_album_{name}_page_{size}',
    'recyclepagedownloadname': 'Trash_page_{size}',
    'downloadfallstotalone': 'Total: 1',
    'downloadfallstotal': 'Total: {size}',
    'operatefailtips': 'Operation failed. Please try again.',
    'noteRichtTxtTips': 'Your rich text notes will be synced here. The online display feature for these notes is coming soon.',
    'noteok': 'OK',
    'menufind': 'Find My',
    'albumremovetips': 'Smart Album is unavailable while it\'s being upgraded. Your data in the cloud will not be affected by this upgrade.'
}